version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2024.01.1
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Make gradlew executable
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew --no-daemon dependencies
      - run:
          name: Run Tests
          command: ./gradlew testDebugUnitTest --no-daemon
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease --no-daemon
      - run:
          name: List build output
          command: ls -R app/build/outputs/

      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: release-apk
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
filters:
  branches:
    only: [ develop ]