version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2024.01.1
    steps:
      - checkout
      - run:
          name: Only run for PRs to develop
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              echo "Not a PR, skipping build."
              circleci-agent step halt
            fi
      - run:
          name: Make gradlew executable
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew --no-daemon dependencies
      - run:
          name: Run Tests
          command: ./gradlew testDebugUnitTest --no-daemon
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease --no-daemon
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: release-apk

workflows:
  version: 2
  pr_to_develop:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            pull_requests:
              only:
                - develop
