version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-33
    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Download Dependencies
          command: ./gradlew --no-daemon dependencies

      - run:
          name: Run Tests
          command: ./gradlew testDebugUnitTest --no-daemon

      - run:
          name: Build APK
          command: ./gradlew assembleDebug --no-daemon

      - persist_to_workspace:
          root: ~/app
          paths:
            - app/build/outputs/apk/debug/app-debug.apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
